// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: vector_service.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VectorService_SearchSimilarVectors_FullMethodName = "/vector.v1.VectorService/SearchSimilarVectors"
	VectorService_InsertBatch_FullMethodName          = "/vector.v1.VectorService/InsertBatch"
)

// VectorServiceClient is the client API for VectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorServiceClient interface {
	// SearchSimilarVectors finds top-K most similar vectors to a query embedding.
	SearchSimilarVectors(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// InsertBatch adds a batch of vector embeddings into the system.
	InsertBatch(ctx context.Context, in *InsertBatchRequest, opts ...grpc.CallOption) (*InsertBatchResponse, error)
}

type vectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorServiceClient(cc grpc.ClientConnInterface) VectorServiceClient {
	return &vectorServiceClient{cc}
}

func (c *vectorServiceClient) SearchSimilarVectors(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, VectorService_SearchSimilarVectors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) InsertBatch(ctx context.Context, in *InsertBatchRequest, opts ...grpc.CallOption) (*InsertBatchResponse, error) {
	out := new(InsertBatchResponse)
	err := c.cc.Invoke(ctx, VectorService_InsertBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorServiceServer is the server API for VectorService service.
// All implementations must embed UnimplementedVectorServiceServer
// for forward compatibility
type VectorServiceServer interface {
	// SearchSimilarVectors finds top-K most similar vectors to a query embedding.
	SearchSimilarVectors(context.Context, *SearchRequest) (*SearchResponse, error)
	// InsertBatch adds a batch of vector embeddings into the system.
	InsertBatch(context.Context, *InsertBatchRequest) (*InsertBatchResponse, error)
	mustEmbedUnimplementedVectorServiceServer()
}

// UnimplementedVectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVectorServiceServer struct {
}

func (UnimplementedVectorServiceServer) SearchSimilarVectors(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchSimilarVectors not implemented")
}
func (UnimplementedVectorServiceServer) InsertBatch(context.Context, *InsertBatchRequest) (*InsertBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertBatch not implemented")
}
func (UnimplementedVectorServiceServer) mustEmbedUnimplementedVectorServiceServer() {}

// UnsafeVectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorServiceServer will
// result in compilation errors.
type UnsafeVectorServiceServer interface {
	mustEmbedUnimplementedVectorServiceServer()
}

func RegisterVectorServiceServer(s grpc.ServiceRegistrar, srv VectorServiceServer) {
	s.RegisterService(&VectorService_ServiceDesc, srv)
}

func _VectorService_SearchSimilarVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).SearchSimilarVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_SearchSimilarVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).SearchSimilarVectors(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_InsertBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).InsertBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_InsertBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).InsertBatch(ctx, req.(*InsertBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorService_ServiceDesc is the grpc.ServiceDesc for VectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vector.v1.VectorService",
	HandlerType: (*VectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchSimilarVectors",
			Handler:    _VectorService_SearchSimilarVectors_Handler,
		},
		{
			MethodName: "InsertBatch",
			Handler:    _VectorService_InsertBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vector_service.proto",
}
